services:
  migration:
    image: ghcr.io/mahaveer1141/sound-stage:latest
    entrypoint: ["goose", "-dir", "/app/migrations", "up"]
    env_file: .sound_stage.env
    networks:
      - ms_platforms_network

  app:
    image: ghcr.io/mahaveer1141/sound-stage:latest
    container_name: sound_stage_app
    restart: unless-stopped
    depends_on:
      migration:
        condition: service_completed_successfully
    ports:
      - "${SERVER_PORT:-8000}:8000"
    env_file: .sound_stage.env
    networks:
      - ms_platforms_network

networks:
  ms_platforms_network:
    external: true
